id: PF4744A77
initial_creation_type: ocr
source_metadata:
  volumes:
    36d97568c8cf4b20a661305020b0b698:
      base_file: v066.txt
      image_group_id: I1PD95911
      title: རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་དང་པོའི་རྣམ་པར་དབྱེ་བ་བཤད་པ།
      total_pages: 1470
      volume_number: 66
